---
version: 2

build:
  os: "ubuntu-lts-latest"
  tools:
    python: "3.13"
  jobs:
    install:
      - pip install -U pip
      - pip install -e .
      - pip install --group 'docs'

sphinx:
  configuration: docs/source/conf.py
  # fail_on_warning: true

# formats:
#   - pdf
#   - epub
