---
name: tests

"on":
  push:
  pull_request:

env:
  UV_PYTHON_DOWNLOADS: never
  UV_LOCKED: "true"

jobs:

  misc:
    name: "Linting configs"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v7
        with:
          fetch-depth: 12
      - name: "Setup Python"
        uses: actions/setup-python@v7
        with:
          python-version: "3.14"
      - name: "Setup uv"
        uses: astral-sh/setup-uv@v8.2.0
      - name: "Setup just"
        uses: extractions/setup-just@v4
      - name: "Check uv.lock"
        run: just lock-check
      - name: "Lint TOMLs"
        run: just lint-toml
      - name: "Lint YAMLs"
        run: just lint-yaml

  lint:
    name: "Linting"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v7
      - name: "Setup Python"
        uses: actions/setup-python@v7
        with:
          python-version: "3.14"
      - name: "Setup uv"
        uses: astral-sh/setup-uv@v8.2.0
      - name: "Setup just"
        uses: extractions/setup-just@v4
      - name: "Lint formatting"
        run: just lint

  typing:
    name: "Type checking (library code)"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v7
      - name: "Setup Python"
        uses: actions/setup-python@v7
        with:
          python-version: "3.14"
      - name: "Setup uv"
        uses: astral-sh/setup-uv@v8.2.0
      - name: "Setup just"
        uses: extractions/setup-just@v4
      - name: "Type checking (library code)"
        run: just typing

  public-typing:
    name: "Type checking (public API)"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v7
      - name: "Setup Python"
        uses: actions/setup-python@v7
        with:
          python-version: "3.14"
      - name: "Setup uv"
        uses: astral-sh/setup-uv@v8.2.0
      - name: "Setup just"
        uses: extractions/setup-just@v4
      - name: "Type checking (public API)"
        run: just public-typing-all

  tests:
    name: "Run unit tests"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
    steps:
      - name: "Checkout"
        uses: actions/checkout@v7
      - name: "Setup Python"
        uses: actions/setup-python@v7
        with:
          python-version: ${{ matrix.python-version }}
      - name: "Setup uv"
        uses: astral-sh/setup-uv@v8.2.0
      - name: "Setup just"
        uses: extractions/setup-just@v4
      - name: "Run tests"
        run: just test ${{ matrix.python-version }}
